spring:
  application:
    name: MentalHealth
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mental_health?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  ip: localhost
  port: 9000
#  servlet:
#    context-path: /api
mybatis-plus:
  #mybatis-plus会默认将表中的驼峰命名法转换为下划线，关闭默认转换
  configuration:
    map-underscore-to-camel-case: false
    #开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
files:
  upload:
    path: F:/毕业设计/MentalHealth/files/
alipay:
  appId: 2021000122610112
  appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDC+S/fZpERhXWmEGYyx0C2EUXWdqwwXOSKR33j08aJtbvwrtx3b2W4tTMcNsNWh/vDHghsD/ivsSkHwoD+WuZDMMrA22h2t50sXampQYJwBL3W6Dqwg62/Pb5K5ZxNpHasr1NI+fb9b7SqRfthNWLAB4l4AdNZfLqM0hsEafZGy7NIybWqP4R7ziz33yy5ofRo+VY0CX48lXubFV7evShB0ImEuUZGlPTUsTgTwDIXtiM8wtZaOo1NMaEQnBPJdqsWVuNK8shr0BFa7avY/r4bMVDd4bZUk/wm8eiBBs7nYEzongTeaFkMwjwXlS0ZNv03EcQcWZAGm6JpdjRAvGYLAgMBAAECggEBAKbCJHzpp8gZos9fFVn269UNHvNYWtueh+XxUa4rspKT+mPX2z7X62O4rzdBa382HVH7/O4YFvaGCvbVGCj0rB7pu3CJ+GYZk3efwH3ARwTyOUB3LcNNTKzV7Uz35+DMeqgl6JDxIpwPD7HW2zOASq69g4k93nuaX6AUEAGNc5OGJaLr91gYbGfTvTW25TG7hj8KM3KjGplcg+bj/Ljq8AQUcnWmwBDdN/G8Oln2vPsxFYYTOIJOG3jULMB+38C6TbsELICr1tR+0lOXedKGACM+MojYlM9o/f15k2thlEY8hO1ZoMCJLMzRBCJTuO8xE9V+/xLGSfDsAn3XY5TEIOkCgYEA6EV2o9owIkNO9rBVKHxwdwQmGwXJ4zLfY/2TJ5JL4HLBxMxYWEmJ6/ZqBY864ZcZ/kMFWvTvSlsJVazxnHvL1eglGzFRvNoz3cOI8zhXjFd+4g84z1neBRh6UpXj/cBowmYy+7M0H1M9dje5FBVacsVE/i4bVbPkS2XMqBMTXm0CgYEA1uRHdEd9sNHHCL92M0cBNzHhrxAFVTRq8/jCi6PJD4KQ0HdkbxRX2q+XpYHjwzEegTBzYMffRfcPPJfpJNPtIHMP8jbPs1ErfaB5R8m+gaaxwNwU/AGfKgvOdisNeyZenrEscXLhaJsnHZM0wydkvaz7MfidAqF/vPGTvNqXK1cCgYAFTyEpGaGkBtnVNa6coEuJzOR6FaXJta35gSBN9UAav0TClNEoI3YtmJJP0jhMU8HaV/nVXGfj0TTjanKTWxkLqKTAfF4b7PjmhsOom48UvCNAU4y+4JT8lNSm8polgLJkTyW3Lx9v3901yIxIczyABxZOoQsq6FO9jXQiG12D+QKBgQCOU1d4DjmTOP2IL7cLs0V81w7Qsd22VydXOzUu42WxXhqn18uvPlwJvS7FMcg2aXv4uKxSN08Ludxfl4WVHL/7M/olxGPAMkyJwhVRlK8Wk987Cwji9/gBExzFazJclEcq99Gluh7M96XqkqrpblfswHsG19C2A1zlOWNOO8DPtQKBgQDfZnmPQ372ikfKT3/4wFVoa24+sjmtCU+d0UWMNqHTUj1W5S1NfM0RbujtdXZSeON5aeh/PuVKE1Oe8SIgIhtzy95B2pxqiWoDR5AhzcLeWqBDLc4Uh7P333E5Najox5SLRujyhMf+/d4ssP9rAxouVfeWY1YrTOlXA1nDUw9uTQ==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhF3fvJ5aQ4YBm4ZrNO8qrPyreldP601z/PrZeXd/nrcvMNaINdjV4GzXObEC6j4akrnd9d3rqsdqkqEsDxc5xUOsWvud5dEOULnGRgg1XsSSxGDH8/2755bmbgvQQTHuxykE7InVtD9AR9G4APf0lLYv9dlx9rsmu/0ZLDZJ9e+VNwlrtxtHbkIXB5m9ytbUxqabDiVYhBvxrBxULl/tr9dlGgjhRWnkAW2NgZRB/0Gnnw4ycCYMrXmgPJtlW7cITCW69+H8mSQoNxHigt+T09ebXHhurJv9QhsDPzJ60Cd5kzJ+TPwAy45bzGBdPb8gipKvBprHACEK6oWecDcqyQIDAQAB
  notifyUrl:   http://75k45q.natappfree.cc/alipay/notify
  returnUrl: http://localhost:/front/courseDetail